media: media
content:
  - name: index
    label: Portada
    path: index.md
    type: file
    fields:
      - name: title
        label: Título de la web
        type: string
      - name: description
        label: Subtitulo
        type: string
      - name: videos
        label: Videos
        type: string
        list: true
        description: Videos (poner codigo de youtube)
